###read all users
GET http://localhost:4000/user-api/users

###get user by id
GET http://localhost:4000/user-api/users/697ee76bc9ba1f2ad648b800
###create user

POST http://localhost:4000/user-api/users
Content-Type:application/json

{
    "username":"manu",
    "password":"manu123",
    "age":20
}

###modify user

PUT http://localhost:4000/user-api/user/697ee76bc9ba1f2ad648b800
Content-Type:application/json

{
    "username":"santu",
    "password":"santu12",
    "age":23
}

###delete user

DELETE http://localhost:4000/user-api/user/697dc17dd45368b015bec1c1





###get products

GET http://localhost:4000/product-api/products

###create a product

POST http://localhost:4000/product-api/product
Content-Type:application/json

{
    "pid":100,
    "productName":"kitkat",
    "price":20
}

###get product by id
GET http://localhost:4000/product-api/product/697dd23d0fa7cb182185d664

###modify the product

PUT http://localhost:4000/product-api/product/697dd23d0fa7cb182185d664
Content-Type:application/json

{
    "pid":100,
    "productName":"maggi",
    "price":30,
}

###delete the product

DELETE http://localhost:4000/product-api/product/697ef1d1115cfed7c4e3a248

###user authentication(Login)
POST http://localhost:4000/user-api/auth
Content-Type:application/json

{
    "username":"manu",
    "password":"manu123",
    "age":20
}

###req for protected route
GET http://localhost:4000/user-api/test